name: srpm
description: The Simple Reverse Proxy Manager
version: 1.0.1
repository: https://github.com/University-Of-Fool/srpm

environment:
  sdk: ">=2.19.2 <3.0.0"

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  lints: ^2.0.0
  test: ^1.21.0

dependencies:
  args: ^2.4.0
  json_annotation: ^4.8.0
  nanoid: ^1.0.0
  toml: ^0.14.0
